# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Sprachübergreifende-Textalignierung" data-toc-modified-id="Sprachübergreifende-Textalignierung-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Sprachübergreifende Textalignierung</a></div><div class="lev1 toc-item"><a href="#Manuales-(sprachübergreifende-Alignierung)" data-toc-modified-id="Manuales-(sprachübergreifende-Alignierung)-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Manuales (sprachübergreifende Alignierung)</a></div>

# Sprachübergreifende Textalignierung

Blockseminar Studiengang "Digitale Methodik in den Geistes- und Kulturwissenschaften" (18.1.2020, 8.2.2020, 15.2.2020)




In [8]:
import os

in_dir = "./data/constitutions/"

# we create a dictionary with our constitutions:
sources = {}

for file in sorted(os.listdir(in_dir)):
    key = os.path.basename(file).split(os.extsep)[0]
    with open(in_dir + '/' + file, encoding="utf-8") as f:
        sources[key] = f.read()

# and a list of available constitutions for quick lookup:
constitutions = list(sources.keys())

print ("{} files read:".format(len(constitutions)))
print (constitutions)

5 files read:
['1867_-_GB-NA_-_Great_Britain_-_british_north_american_act', '1909_-_GB-SA_-_Great_Britain_-_british_south_africa_act', '1935_-_GB-BU_-_Great_Britain_-_british_government_of_burma_act', '1937_-_IE_-_Ireland_-_constitution_of_ireland', '1948_-_BU_-_Burma_-_constitution_of_burma']


In [2]:
from nltk import tokenize
# nltk.download('punkt')

sentences = {}
nos = {}
for c in constitutions:
    t = tokenize.sent_tokenize(sources[c])
    nos[c] = len(t)
    for i, s in enumerate(t):
        sentences[c + '_' + str(i)] = s

boundary = len(sentences) - nos['1948_-_BU_-_Burma_-_constitution_of_burma']
print("Corpus has {} sentences.".format(len(sentences)))
print("1948_-_BU_-_Burma_-_constitution_of_burma has {}.\n".format(nos['1948_-_BU_-_Burma_-_constitution_of_burma']))

print("Its first 3 sentences are:\n{}".format([sentences['1948_-_BU_-_Burma_-_constitution_of_burma_0'],\
                                              sentences['1948_-_BU_-_Burma_-_constitution_of_burma_1'],\
                                              sentences['1948_-_BU_-_Burma_-_constitution_of_burma_2']]))

Corpus has 3240 sentences.
1948_-_BU_-_Burma_-_constitution_of_burma has 963.

Its first 3 sentences are:
['The Constitution of the Union of Burma, 24 September 1947, Effective 4 January 1948\n\nPREAMBLE\nWE, THE PEOPLE OF BURMA including the Frontier Areas and the Karenni States, Determined to establish in strength and unity a\nSOVEREIGN INDEPENDENT STATE, To maintain social order on the basis of the eternal principles of JUSTICE, LIBERTY AND EQUALITY\nand To guarantee and secure to all citizens JUSTICE social, economic and political; LIBERTY of thought, expression, belief,\nfaith, worship, vocation, association and action; EQUALITY of status, of opportunity and before the law, IN OUR CONSTITUENT\nASSEMBLY this Tenth day of Thadingyut waxing, 1309 B.E.', '(Twentyfourth day of September, 1947 A.D.), DO HEREBY ADOPT,\nENACT AND GIVE TO OURSELVES THIS CONSTITUTION.', 'CHAPTER I.']


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(analyzer='word', strip_accents='unicode', stop_words=["the", "of", "and"])
dfm = vectorizer.fit_transform(sentences.values())

print(dfm.shape)
print(type(dfm))
print(dfm.toarray())

(3240, 4685)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
from sklearn.metrics.pairwise import cosine_similarity

target = dfm[boundary:]
sources = dfm[:boundary,]
print(target.shape)
print(sources.shape)

simils = cosine_similarity(target, sources)
print(simils.shape)

(963, 4685)
(2277, 4685)
(963, 2277)


In [7]:
import numpy as np

np.argmax(simils, axis=1)

array([1703, 1898,   89,  589,    0, 1741,    0, 1334,    0,  499,    0,
       1905,    0, 1757,    0, 1765,    0, 1765,    0, 2099,    6, 2199,
        589,    0,  536, 1911,  992,  927,  994, 1475,  997,  256, 2199,
        999, 1313,  529, 1680, 1005, 1749, 2199, 1007, 2206, 1009, 2213,
       2216, 2218, 2198, 1653, 1012, 2161, 1014,  948,    0, 1571, 1011,
       1016, 2241,    0, 2155,    0, 2200, 1018, 2239, 2240, 2243, 2272,
       2199, 1020, 2014, 2199, 1022, 2233, 2234, 1888, 2215, 2272, 1297,
       1024, 1426, 1349, 1026, 2272, 1653, 2102, 1198, 1043, 1200, 2102,
       1206, 1230, 1209, 2274,   20, 1659, 1215, 1902, 1690,  615, 1947,
       1217, 1916, 1349,   38, 2247, 1220, 2247, 2248, 1226, 2234,  797,
       1232, 2230, 1236, 2249, 1240, 1995, 1243, 2258, 2224, 1247, 2130,
       1251, 1577, 1254,  589, 2201, 1258,    7, 1262, 2200, 1376,  645,
        531,  648,  789,  789,  570, 1283, 1919, 1286, 1920, 1931, 1294,
       1932, 1933, 1934,  659, 1923, 1833, 1303, 19

# Manuales (sprachübergreifende Alignierung)

In [2]:
import os

in_dir = "./data/manual/"

# we create a dictionary with our manuales:
sources = {}

for file in sorted(os.listdir(in_dir)):
    key = os.path.basename(file).split(os.extsep)[0]
    with open(in_dir + '/' + file, encoding="utf-8") as f:
        sources[key] = f.read()

# and a list of available constitutions for quick lookup:
manuales = list(sources.keys())

print ("{} files read:".format(len(manuales)))
print (manuales)

3 files read:
['azp1552_ch17', 'azp1556_ch17', 'azp1573_ch17']


In [5]:
from nltk import tokenize
# nltk.download('punkt')

sentences = {}
nos = {}
for c in manuales:
    t = tokenize.sent_tokenize(sources[c])
    nos[c] = len(t)
    for i, s in enumerate(t):
        sentences[c + '_' + str(i)] = s

print("Corpus has {} sentences.".format(len(sentences)))
print("azp1552_ch17 {}.\n".format(nos['azp1552_ch17']))

print("Its first 3 sentences are:\n{}".format([sentences['azp1552_ch17_2'],\
                                              sentences['azp1552_ch17_3'],\
                                              sentences['azp1552_ch17_4']]))

Corpus has 23208 sentences.
azp1552_ch17 5477.

Its first 3 sentences are:
['S. Franci<g ref="#char017f">ſ</g>co <lb xml:id="Azp1552-00-0007-lb-0008"/>da\n                    prouincia da piedade: E vi<g ref="#char017f">ſ</g>to <g ref="#char0026">&amp;</g> em <choice xml:id="d2e2063"><abbr>alg<g ref="#charu0303">ũ</g>s</abbr><expan resp="#auto">alguns</expan></choice> <lb xml:id="Azp1552-00-0007-lb-0009"/>pa<g ref="#char017f">ſ</g><g ref="#char017f">ſ</g>os declarado polo muy famo<g ref="#char017f">ſ</g>o Doutor <lb xml:id="Azp1552-00-0007-lb-0010"/>Martim de Azpilcueta Nauarro, cathredati<lb xml:id="Azp1552-00-0007-lb-0011" break="no" rendition="#hyphen"/>co iubilado de\n                    Prima em Canones na vniuer<lb break="no" rendition="#noHyphen" xml:id="Azp1552-00-0007-lb-0012"/><g ref="#char017f">ſ</g>idade de Coimbra.', 'E de<g ref="#char017f">ſ</g>pois <choice xml:id="d2e2091"><abbr>c<g ref="#charo0303">õ</g></abbr><expan resp="#auto">com</expan></choice> <g ref="#char017f">

In [23]:
import lxml
from lxml import etree
# import re

parsed = { os.path.basename(file).split(os.extsep)[0] :
                 (etree.parse(in_dir + "/" + file))
                     for file in sorted(os.listdir(in_dir))
         }

nsmap = {"tei": "http://www.tei-c.org/ns/1.0"}

def flatten(element: lxml.etree._Element):
    t = ""
    if element.text:
        t += str.replace(element.text, "\n", " ")
    if element.getchildren():
        t += " ".join((flatten(child)) for child in element.getchildren())
    if element.tail:
        t += str.replace(element.tail, "\n", " ")
    return t

xp_divs = etree.XPath("(//tei:body/tei:div[@type = 'chapter'][not(@n = '0')])", namespaces = nsmap)

divs = {}
t = {}

for c in manuales:
    divs[c] = xp_divs(parsed[c])

    t[c] = "".join("++div_" + str(div.get("n")) + "--" + flatten(div) for div in divs[c])

print("t[azp1552_ch17] is '{}'.".format(t['azp1552_ch17'][:400]))

t[azp1552_ch17] is '++div_17--   ¶ Do  ſeptimo mandamento. N ão furtaras.  Capit. xvi j̈.    PEra fundamento   das preguntas  de ſte  mãdam ẽto mandamento di ʒemos. Ho pri meyro que ha hi furto m ẽtal,  ⁊ fur to real. Ho m ẽtal he  võtade vontade de co meter ho real. Eho real he  ſeg ũdo segundo  Paulo  l. 1. ff.  đ fur.  .§. 1. In ſtit.  de obligat.  qu æ ex de  li. na ſc. contrata ç ã, ou tratam ẽto  engano ſa '.


In [26]:
sentences = {}
nos = {}
for c in manuales:
    segments = tokenize.sent_tokenize(t[c])
    nos[c] = len(segments)
    for i, s in enumerate(segments):
        sentences[c + '_' + str(i)] = s

print("Corpus has {} sentences.".format(len(sentences)))
print("azp1552_ch17 {}.\n".format(nos['azp1552_ch17']))

print("Its first 10 sentences are:\n{}".format([sentences['azp1552_ch17_0'],\
                                              sentences['azp1552_ch17_1'],\
                                              sentences['azp1552_ch17_2'],\
                                              sentences['azp1552_ch17_3'],\
                                              sentences['azp1552_ch17_4'],\
                                              sentences['azp1552_ch17_5'],\
                                              sentences['azp1552_ch17_6'],\
                                              sentences['azp1552_ch17_7'],\
                                              sentences['azp1552_ch17_8'],\
                                              sentences['azp1552_ch17_9']]))

Corpus has 19522 sentences.
azp1552_ch17 5054.

Its first 10 sentences are:
['++div_17--   ¶ Do  ſeptimo mandamento.', 'N ão furtaras.', 'Capit.', 'xvi j̈.', 'PEra fundamento   das preguntas  de ſte  mãdam ẽto mandamento di ʒemos.', 'Ho pri meyro que ha hi furto m ẽtal,  ⁊ fur to real.', 'Ho m ẽtal he  võtade vontade de co meter ho real.', 'Eho real he  ſeg ũdo segundo  Paulo  l. 1. ff.', 'đ fur.', '.§.']
